from typing import Protocol, List
from ..models import Recording

class RecordingRepository(Protocol):
    def create_recording(self, user_id: str) -> Recording: ...
    def get_recording(self, recording_id: str) -> Recording: ...
    def list_recordings(self, user_id: str) -> List[Recording]: ...
    def add_chunk(self, recording_id: str, chunk_path: str, index: int) -> None: ...
    def mark_paused(self, recording_id: str) -> None: ...
    def mark_ended(self, recording_id: str, full_audio_path: str, transcription: str) -> None: ...